# application: hansenmaddy
# version: 1
runtime: python27
threadsafe: false

handlers:

  # domain switcher
- url: /
  script: switch.py

- url: /index\.html
  script: switch.py

  # ladyOnIctProjects
- url: /loip/css/
  static_dir: ladyOnIctProjects/css/

- url: /loip/img/
  static_dir: ladyOnIctProjects/img/

  # hand en Maddy
- url: /plaatjes/
  static_dir: img/

  # zuidvast
- url: /zv/css/
  static_dir: zuidvast/css/

- url: /zv/img/
  static_dir: zuidvast/img/

- url: /zv/js/
  static_dir: zuidvast/js/

- url: /index2.html
  script: zuidvast.py

- url: /index3.html
  script: zuidvast3.py

  # bijna2010
- url: /signup.*
  script: switch.py

- url: /2010/css/
  static_dir: bijna2010/css/

- url: /2010/img/
  static_dir: bijna2010/img/

- url: /2010/js/
  static_dir: bijna2010/js/

- url: /index.html
  script: bijna2010.py

  # ccxlv
- url: /ccxlv/css/
  static_dir: ccxlv/css/

- url: /ccxlv/img/
  static_dir: ccxlv/img/

  # mannenweekend 2008
- url: /mannenweekend2008.*
  script: mannenweekend2008.py

- url: /mw/img/
  static_dir: mw2008/img/

  # other stuff
- url: /.*
  script: switch.py
  # script: not_found.py

#- url: /(.*\.(gif|png|jpg))
#  static_files: ladyOnIctProjects/img/
#  upload: ladyOnIctProjects/img/(.*\.(gif|png|jpg))

#- url: /admin/.*
#  script: admin.py
#  login: admin
